CREATE TABLE "EXPENSE" (
  "ID" INTEGER UNSIGNED NOT NULL,
  "INSERT_USER" VARCHAR(45),
  "INSERT_TIME" DATETIME,
  "UPDATE_USER" VARCHAR(45),
  "UPDATE_TIME" DATETIME,
  "NUMBER" DOUBLE,
  "COST" DOUBLE,
  "TIME" DATETIME,
  "NOTE" VARCHAR(1000),
  "ITEM_ID" INTEGER UNSIGNED,
  PRIMARY KEY ("ID")
)